[package]
name = "concrete-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete = { version="0.1.11", features=["unsafe"]}
rand = "0.8.4"
